   "# Uncomment and write your prefered text editor:" // new_line('a') //   &
   "#EDITOR=nano" // new_line('a') //                                       &
   "" // new_line('a') //                                                   &
   "[description]" // new_line('a') //                                      &
   "" // new_line('a') //                                                   &
   "Yet another fBlog website" // new_line('a') //                          &
   "" // new_line('a') //                                                   &
   "[footer]" // new_line('a') //                                           &
   "" // new_line('a') //                                                   &
   "<address>" // new_line('a') //                                          &
   'Powered by <a href="http://sourceforge.net/' //                         &
      'projects/fortranblog">fBlog</a>' // new_line('a') //                 &
   "</address >" // new_line('a') //                                        &
   "" // new_line('a') //                                                   &
   "[translation]" // new_line('a') //                                      &
   "" // new_line('a') //                                                   &
   "HOME=Home" // new_line('a') //                                          &
   "ARCHIVE=Archives" // new_line('a') //                                   &
   "PERMALINK=permalink" // new_line('a') //                                &
   "PRINTER_FRIENDLY=printer-friendly page" // new_line('a') //             &
   "" // new_line('a') //                                                   &
   "JANUARY=jan" // new_line('a') //                                        &
   "FEBRUARY=feb" // new_line('a') //                                       &
   "MARCH=mar" // new_line('a') //                                          &
   "APRIL=apr" // new_line('a') //                                          &
   "MAY=may" // new_line('a') //                                            &
   "JUNE=jun" // new_line('a') //                                           &
   "JULY=jul" // new_line('a') //                                           &
   "AUGUST=aug" // new_line('a') //                                         &
   "SEPTEMBER=sep" // new_line('a') //                                      &
   "OCTOBER=oct" // new_line('a') //                                        &
   "NOVEMBER=nov" // new_line('a') //                                       &
   "DECEMBER=dec" // new_line('a') //                                       &
   "" // new_line('a') //                                                   &
   "[menu]" // new_line('a') //                                             &
   "" // new_line('a') //                                                   &
   "# Left side: label. Right side: any URL or" //                          &
      " filename of a given page." // new_line('a') //                      &
   "# MyLabel=http://www.example.com/" // new_line('a') //                  &
   "" // new_line('a') //                                                   &
   "Page #1=page1.html" // new_line('a') //                                 &
   "Page #2=page2.html" // new_line('a') //                                 &
   "Page #3=page3.html" // new_line('a') //                                 &
   "" // new_line('a') //                                                   &
   "# End of configuration file."