  "# Configuration file of fBlog." // new_line('a') //                     &    
  "" // new_line('a') //                                                   &    
  "[global]" // new_line('a') //                                           &    
  "" // new_line('a') //                                                   &    
  "TITLE=My Blog" // new_line('a') //                                      &    
  "" // new_line('a') //                                                   &    
  "CHARSET=UTF-8" // new_line('a') //                                      &    
  "" // new_line('a') //                                                   &    
  "LANG=en" // new_line('a') //                                            &    
  "" // new_line('a') //                                                   &    
  "#  rtl' is for languages written from right to left."                   &    
  // new_line('a') //                                                      &    
  "#DIRECTION=rtl" // new_line('a') //                                     &    
  "" // new_line('a') //                                                   &    
  "#  Number of posts at home page. (Default is ten)." // new_line('a') // &    
  "MAX_ENTRIES=10" // new_line('a') //                                     &    
      "" // new_line('a')