   'html {' // new_line('a') // &
   '     background: #ddd;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'body {' // new_line('a') // &
   '   margin-top: 50px;' // new_line('a') // &
   '   padding-top: 10px;' // new_line('a') // &
   '   max-width: 1100px;' // new_line('a') // &
   '   margin-left: auto;' // new_line('a') // &
   '   margin-right: auto;' // new_line('a') // &
   '   min-width: 780px;' // new_line('a') // &
   '   box-shadow: 0px 0px 7px 5px silver;' // new_line('a') // &
   '   border: #eee solid thin;' // new_line('a') // &
   '   border-radius: 5px;' // new_line('a') // &
   '   background: white;' // new_line('a') // &
   '   font-size: 12pt;' // new_line('a') // &
   '   font-family: "Verdana", "Geneva", "Arial", "Lucida Grande", "Gill Sans", sans-serif;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'h1, h2, h3 {' // new_line('a') // &
   '   font-weight: normal;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'a:link, a:visited {' // new_line('a') // &
   '   color: #506088;' // new_line('a') // &
   '   background: transparent;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'a:hover {' // new_line('a') // &
   '   color: #ff9040;' // new_line('a') // &
   '   background: transparent;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'a:focus {' // new_line('a') // &
   '   color: #ff9040;' // new_line('a') // &
   '   background: transparent;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'nav > hr, footer > hr {' // new_line('a') // &
   '   display: none;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'dd {' // new_line('a') // &
   '   margin: 0 0 1em 4em;' // new_line('a') // &
   '   font-size: 93%' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'code, pre, samp {' // new_line('a') // &
   '   overflow-x: auto;' // new_line('a') // &
   '   overflow-y: auto;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'pre > code {' // new_line('a') // &
   '   display: block;' // new_line('a') // &
   '   padding: 1em;' // new_line('a') // &
   '   font: bold 10pt "Courier New", courier, monospace;' // new_line('a') // &
   '   color: white;' // new_line('a') // &
   '   border: black thin solid;' // new_line('a') // &
   '   background: #555;' // new_line('a') // &
   '   border-radius: 3px;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'figcaption {' // new_line('a') // &
   '   font-size: smaller;' // new_line('a') // &
   '   text-align: center;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'mark {' // new_line('a') // &
   '   background-color: #ff9040;' // new_line('a') // &
   '   border-radius: 3px;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'body > header {' // new_line('a') // &
   '   position:absolute;' // new_line('a') // &
   '   height: 40px;' // new_line('a') // &
   '   top: 0;' // new_line('a') // &
   '   left: 0;' // new_line('a') // &
   '   right: 0;' // new_line('a') // &
   '   width: auto;' // new_line('a') // &
   '   border-bottom: #506088 thin solid;' // new_line('a') // &
   '   background: #8090a8;' // new_line('a') // &
   '   background: linear-gradient(#99acc8, #8090a8);' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'body > header > h1 {' // new_line('a') // &
   '   margin: 0;' // new_line('a') // &
   '   text-align: center;' // new_line('a') // &
   '   font-size: 30px;' // new_line('a') // &
   '   font-weight: bold;' // new_line('a') // &
   '   text-shadow: 0 2px #777;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   '/* Title of the blog */' // new_line('a') // &
   'body > header > h1 > a {' // new_line('a') // &
   '   text-decoration: none;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'body > header > h1 > a:link {' // new_line('a') // &
   '   color: white;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'body > header > h1 > a:visited {' // new_line('a') // &
   '   color: white;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'body > header > h1 > a:hover {' // new_line('a') // &
   '   color: #ff9040;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'body > header > h1 > a:focus {' // new_line('a') // &
   '   text-shadow: none;' // new_line('a') // &
   '   color: #ff9040;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   '/* Description of the blog */' // new_line('a') // &
   'body > aside {' // new_line('a') // &
   '   width: 200px;' // new_line('a') // &
   '   margin: 20px 10px 40px 10px;' // new_line('a') // &
   '   padding: 5px;' // new_line('a') // &
   '   font-size: 14px;' // new_line('a') // &
   '   text-align: center;' // new_line('a') // &
   '   font-style: italic;' // new_line('a') // &
   '   border-radius: 5px;' // new_line('a') // &
   '   float: left;' // new_line('a') // &
   '   clear: both;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'body > nav > a {' // new_line('a') // &
   '   text-decoration: none;' // new_line('a') // &
   '   border: #2C354B solid thin;' // new_line('a') // &
   '   box-shadow: 0 2px #999;' // new_line('a') // &
   '   border-radius: 5px;' // new_line('a') // &
   '   margin: 0.35ex 0 ;' // new_line('a') // &
   '   text-align: center;' // new_line('a') // &
   '   padding: 0.7ex 10px;' // new_line('a') // &
   '   font-weight: bold;' // new_line('a') // &
   '   text-shadow: 0 1px #555;' // new_line('a') // &
   '   font-size: 13px;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'body > nav > a:link {' // new_line('a') // &
   '   color: white;' // new_line('a') // &
   '   background: #506088;' // new_line('a') // &
   '   background: linear-gradient(#5e72a0, #506088);' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'body > nav > a:visited {' // new_line('a') // &
   '   color: white;' // new_line('a') // &
   '   background: #506088;' // new_line('a') // &
   '   background: linear-gradient(#5e72a0, #506088);' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'body > nav > a:hover {' // new_line('a') // &
   '   background: #8090a8;' // new_line('a') // &
   '   background: linear-gradient(#99acc8, #8090a8);' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'body > nav > a:focus {' // new_line('a') // &
   '   box-shadow: none;' // new_line('a') // &
   '   background: #8090a8;' // new_line('a') // &
   '   background: linear-gradient(#99acc8, #8090a8);' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'header + nav:first-of-type {' // new_line('a') // &
   '   padding-top: 60px;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'body > nav:first-of-type {' // new_line('a') // &
   '   width: 200px;' // new_line('a') // &
   '   margin: 0 0 20px 10px;' // new_line('a') // &
   '   float: left;' // new_line('a') // &
   '   clear: both;' // new_line('a') // &
   '   color: transparent ;' // new_line('a') // &
   '   font-size: 0;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   '/* Top arrows and bottom arrow of main page. */' // new_line('a') // &
   'body > nav > a[rel] {' // new_line('a') // &
   '   display: inline;' // new_line('a') // &
   '   width: 60px;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'body > nav:first-of-type > a[rel="prev"] {' // new_line('a') // &
   '   margin: 0 10px 2ex 0;' // new_line('a') // &
   '   float: right;' // new_line('a') // &
   '   clear: right;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'body > nav:first-of-type > a[rel="next"] {' // new_line('a') // &
   '   margin: 0 0 2ex 10px;' // new_line('a') // &
   '   float: left;' // new_line('a') // &
   '   clear: right;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   '' // new_line('a') // &
   '/* Menu items */' // new_line('a') // &
   'body > nav:first-of-type > a {' // new_line('a') // &
   '   clear: both;' // new_line('a') // &
   '   display: block;' // new_line('a') // &
   '}'