   '/* Menu items */' // new_line('a') // &
   'body > nav:first-of-type > a {' // new_line('a') // &
   '   margin: 0 3px;' // new_line('a') // &
   '   padding: 2px 5px;' // new_line('a') // &
   '   display: inline;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   '/* Top arrows */' // new_line('a') // &
   'body > nav:first-of-type > a[rel] {' // new_line('a') // &
   '   float: none;' // new_line('a') // &
   '   margin: 0 3px;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'body > nav:first-of-type > a[rel="prev"] {' // new_line('a') // &
   '   margin-right: 15px;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   '/* Articles */' // new_line('a') // &
   'article {' // new_line('a') // &
   '   margin: 0;' // new_line('a') // &
   '   padding: 0 20px;' // new_line('a') // &
   '   border: none;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'html[dir="rtl"] body > aside {' // new_line('a') // &
   '   width: auto;' // new_line('a') // &
   '   padding: 5px 15px;' // new_line('a') // &
   '   margin: 0;' // new_line('a') // &
   '   text-align: inherit;' // new_line('a') // &
   '   float: none;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'html[dir="rtl"] body > nav:first-of-type {' // new_line('a') // &
   '   margin: auto 0 0 0;' // new_line('a') // &
   '   float: none;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'html[dir="rtl"] header+nav:first-of-type {' // new_line('a') // &
   '   margin-top: 5px;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'html[dir="rtl"] body > nav:first-of-type > a[rel] {' // new_line('a') // &
   '   float: none;' // new_line('a') // &
   '   margin: 0 3px;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'html[dir="rtl"] body > nav:first-of-type > a[rel="prev"] {' // new_line('a') // &
   '   margin-left: 15px;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'html[dir="rtl"] article {' // new_line('a') // &
   '   margin: 0;' // new_line('a') // &
   '   padding: 0 20px;' // new_line('a') // &
   '   border: none;' // new_line('a') // &
   '}' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   '@media screen and (orientation:portrait) {' // new_line('a') // &
   '' // new_line('a') // &
   'body {' // new_line('a') // &
   '   width: auto;' // new_line('a') // &
   '   margin: 0;' // new_line('a') // &
   '   padding-top: 0;' // new_line('a') // &
   '   min-width: 480px;' // new_line('a') // &
   '   font-size: 12pt;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'body > header {' // new_line('a') // &
   '   position: relative;' // new_line('a') // &
   '   margin: -1px;' // new_line('a') // &
   '   padding: 0;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   '/* Description of the blog */' // new_line('a') // &
   'body >  aside {' // new_line('a') // &
   '   width: auto;' // new_line('a') // &
   '   padding: 5px 15px;' // new_line('a') // &
   '   margin: 0;' // new_line('a') // &
   '   text-align: inherit;' // new_line('a') // &
   '   float: none;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'body > nav:first-of-type {' // new_line('a') // &
   '   width: auto;' // new_line('a') // &
   '   margin: 0;' // new_line('a') // &
   '   padding: 5px 10px 7px 10px;' // new_line('a') // &
   '   border-top: #506088 thin solid;' // new_line('a') // &
   '   border-bottom: #506088 thin solid;' // new_line('a') // &
   '   float: none;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'header+nav:first-of-type {' // new_line('a') // &
   '   margin-top: 5px;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   '/* Menu items */' // new_line('a') // &
   'body > nav:first-of-type > a {' // new_line('a') // &
   '   margin: 0 3px;' // new_line('a') // &
   '   padding: 2px 5px;' // new_line('a') // &
   '   display: inline;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   '/* Top arrows */' // new_line('a') // &
   'body > nav:first-of-type > a[rel] {' // new_line('a') // &
   '   float: none;' // new_line('a') // &
   '   margin: 0 3px;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'body > nav:first-of-type > a[rel="prev"] {' // new_line('a') // &
   '   margin-right: 15px;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   '/* Articles */' // new_line('a') // &
   'article {' // new_line('a') // &
   '   margin: 0;' // new_line('a') // &
   '   padding: 0 20px;' // new_line('a') // &
   '   border: none;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'html[dir="rtl"] body > aside {' // new_line('a') // &
   '   width: auto;' // new_line('a') // &
   '   padding: 5px 15px;' // new_line('a') // &
   '   margin: 0;' // new_line('a') // &
   '   text-align: inherit;' // new_line('a') // &
   '   float: none;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'html[dir="rtl"] body > nav:first-of-type {' // new_line('a') // &
   '   margin: auto 0 0 0;' // new_line('a') // &
   '   float: none;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'html[dir="rtl"] header+nav:first-of-type {' // new_line('a') // &
   '   margin-top: 5px;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'html[dir="rtl"] body > nav:first-of-type > a[rel] {' // new_line('a') // &
   '   float: none;' // new_line('a') // &
   '   margin: 0 3px;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'html[dir="rtl"] body > nav:first-of-type > a[rel="prev"] {' // new_line('a') // &
   '   margin-left: 15px;' // new_line('a') // &
   '}' // new_line('a') // &
   '' // new_line('a') // &
   'html[dir="rtl"] article {' // new_line('a') // &
   '   margin: 0;' // new_line('a') // &
   '   padding: 0 20px;' // new_line('a') // &
   '   border: none;' // new_line('a') // &
   '}' // new_line('a') // &
   '}'