'body {' // new_line('a') // &
'   text-align: justify;' // new_line('a') // &
'   font-size: 12pt;' // new_line('a') // &
'   font-family: serif;' // new_line('a') // &
'   hyphens: auto;' // new_line('a') // &
'}' // new_line('a') // &
'' // new_line('a') // &
'p  {' // new_line('a') // &
'   text-indent: 1.0em;' // new_line('a') // &
'}' // new_line('a') // &
'' // new_line('a') // &
'article  img {' // new_line('a') // &
'   max-width: 100%;' // new_line('a') // &
'}' // new_line('a') // &
'' // new_line('a') // &
'@media print and (max-width: 150mm){' // new_line('a') // &
'body {' // new_line('a') // &
'   font-size: 10pt;' // new_line('a') // &
'}' // new_line('a') // &
'}' // new_line('a') // &
'' // new_line('a') // &
'@media screen {' // new_line('a') // &
'body {' // new_line('a') // &
'   padding: 0px 40px;' // new_line('a') // &
'   max-width: 800px;' // new_line('a') // &
'   margin-left: auto;' // new_line('a') // &
'   margin-right: auto;' // new_line('a') // &
'   font-size: 14pt;' // new_line('a') // &
'}' // new_line('a') // &
'}' // new_line('a') // &
'' // new_line('a') // &
'@media screen and (max-width: 1200px){' // new_line('a') // &
'body {' // new_line('a') // &
'   padding: 0 30px;' // new_line('a') // &
'   max-width: 750px;' // new_line('a') // &
'   font-size: 12.5pt;' // new_line('a') // &
'}' // new_line('a') // &
'}' // new_line('a') // &
'' // new_line('a') // &
'@media screen and (max-width: 900px){' // new_line('a') // &
'' // new_line('a') // &
'body {' // new_line('a') // &
'   padding: 0 20px;' // new_line('a') // &
'   max-width: 700px;' // new_line('a') // &
'   font-size: 11pt;' // new_line('a') // &
'}' // new_line('a') // &
'}' // new_line('a') // &
'' // new_line('a') // &
'@media screen and (max-width: 600px) {' // new_line('a') // &
'body {' // new_line('a') // &
'   padding: 0 15px;' // new_line('a') // &
'   font-size: 10.5pt;' // new_line('a') // &
'}' // new_line('a') // &
'}' // new_line('a') // &
'' // new_line('a') // &
'@media screen and (max-width: 450px) {' // new_line('a') // &
'body {' // new_line('a') // &
'   padding: 0 10px;' // new_line('a') // &
'   font-size: 10pt;' // new_line('a') // &
'   min-width: 250px;' // new_line('a') // &
'}' // new_line('a') // &
'}'

