! Copyright (C) 2016 Denis Bernard.
! License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
! This is free software: you are free to change and redistribute it.
! There is NO WARRANTY, to the extent permitted by law.
! Written by Denis Bernard.
!
!! Internationalization of messages according setting of LANG (English, French...)
!
! English translator: Denis BERNARD
! French translator:  Denis BERNARD (mother tongue)
!
!
  msgstr(en,bad_argument) = "Bad argument:"
  msgstr(fr,bad_argument) = "Mauvais argument :"
!
  msgstr(en,begin_update) ="Begin update"
  msgstr(fr,begin_update) ="Début de la mise à jour"
!
  msgstr(en,create_new_blog) = "Create new blog" 
  msgstr(fr,create_new_blog) = "Créer un nouveau blog"
!
  msgstr(en,copy_css) = "Copy CSS to `"
  msgstr(fr,copy_css) = "Copie la feuille de style vers `"
!
  msgstr(en,copy_css_print) = "Copy CSS for printer to `"
  msgstr(fr,copy_css_print) = "Copie la feuille de style des permaliens imprimables vers `"
!
  msgstr(en,deleted) = "deleted"
  msgstr(fr,deleted) = "effacé"
!
  msgstr(en,delete_a_css) = "Delete a style sheet"
  msgstr(fr,delete_a_css) = "Supprimer une feuille de style"
!
  msgstr(en,delete_a_page) = "Delete a page"
  msgstr(fr,delete_a_page) = "Supprimer une page"
!
  msgstr(en,delete_a_post) = "Delete a post"
  msgstr(fr,delete_a_post) = "Supprimer un billet"  
!
  msgstr(en,deleted_file) = "Deleted file:"
  msgstr(fr,deleted_file) = "Supprimé le fichier :"
!
  msgstr(en,deleted_page) = "Deleted page:"
  msgstr(fr,deleted_page) = "Supprimé la page :"
!
  msgstr(en,deleted_you_could_update_the_config) = "deleted. You could update the configuration file!"
  msgstr(fr,deleted_you_could_update_the_config) = "supprimé. Maintenant vous devriez mettre à jour la configuration !"
!
  msgstr(en,edit_a_page) = "New page or modify a page" 
  msgstr(fr,edit_a_page) = "Modifier ou créer une page" 
!
  msgstr(en,edit_a_css) = "New style sheet or modify a style sheet"
  msgstr(fr,edit_a_css) = "Modifier ou créer une feuille de style"
!
  msgstr(en,edited_page) = "Edited page:"
  msgstr(fr,edited_page) = "Édité la page :"
!
  msgstr(en,edit_settings) = "Edit settings"
  msgstr(fr,edit_settings) = "Configurer"
!
  msgstr(en,end_clearing_subdirectory) = "End clearing subdirectory `"
  msgstr(fr,end_clearing_subdirectory) = "Fin du nettoyage du sous-répertoire `"
!
  msgstr(en,enter_the_filename_of_the_css_deleted) = "Enter the file name of the style sheet to be deleted:"
  msgstr(fr,enter_the_filename_of_the_css_deleted) = "Entrez le nom de fichier de la feuille de style à supprimer :"
!
  msgstr(en,enter_the_filename_of_the_page_created) = "Enter the file name of the page to be created or modified:"
  msgstr(fr,enter_the_filename_of_the_page_created) = "Entrez le nom de fichier de la page à créer ou à modifier :"
!
  msgstr(en,enter_the_filename_of_the_page_deleted) = "Enter the file name of the page to be deleted:"
  msgstr(fr,enter_the_filename_of_the_page_deleted) = "Entrez le nom de fichier de la page à supprimer :"
!
  msgstr(en,enter_the_rank_of_the_post_to_delete) = "Enter the rank of the post to delete (the newest one is: < 1 >)"
  msgstr(fr,enter_the_rank_of_the_post_to_delete) = "Entrez le numéro du billet à supprimer (le  plus récent est : <1>)"
!
  msgstr(en,enter_the_rank_of_the_post_to_modify) = "Enter the rank of the post to modify (the newest one is: < 1 >)"
  msgstr(fr,enter_the_rank_of_the_post_to_modify) = "Entrez le numéro du billet à modifier (le plus récent est : <1>)"
!
  msgstr(en,error_css) = "Erroneous CSS name. Please, verify the configuration file."
  msgstr(fr,error_css) = "Nom de la CSS erronnée. Merci de vérifier le fichier de configuration."
!
  msgstr(en,error_css_print) = "Erroneous name CSS for printer. Verify configuration file."
  msgstr(fr,error_css_print) = "Nom de la CSS pour l'imprimante erroné. Merci de vérifier le fichier de configuration."
!
  msgstr(en,files_generated_inside_the_subdirectory) = "files generated within the subdirectory `"
  msgstr(fr,files_generated_inside_the_subdirectory) = "fichiers générés dans le sous-répertoire `"
!
  msgstr(en,initialisation_reading_conf) = "Initialisation 2/2: reading configuration"
  msgstr(fr,initialisation_reading_conf) = "Initialisation 2/2: lecture de la configuration"
!
  msgstr(en,initialisation_reading_data) = "Initialisation 1/2: reading data"
  msgstr(fr,initialisation_reading_data) = "Initialisation 1/2 : lecture des données"
!
  msgstr(en,is_a_wrong_argument) = "is a wrong argument."
  msgstr(fr,is_a_wrong_argument) = "est un mauvais argument."  
!
  msgstr(en,is_deleted) = "deleted:"
  msgstr(fr,is_deleted) = "effacé :"
!
  msgstr(en,make_archive_pages) = "Make archive page `"
  msgstr(fr,make_archive_pages) = "Génère l'index des archives `"
!
  msgstr(en,make_clear_subdirectory) = "Make clear subdirectory `"
  msgstr(fr,make_clear_subdirectory) = "Début du nettoyage du sous-répertoire `"
!
  msgstr(en,make_home_page) = "Make home page `"
  msgstr(fr,make_home_page) = "Génère la page d'accueil `"
!
  msgstr(en,make_pages) = "Make pages `"
  msgstr(fr,make_pages) = "Génère les pages statiques `"
!
  msgstr(en,make_permalink_pages) = "Make permalink pages `"
  msgstr(fr,make_permalink_pages) = "Génère les permaliens `"
!
  msgstr(en,modify_a_post) = "Modify a post"
  msgstr(fr,modify_a_post) = "Modifier un billet"
!
  msgstr(en,monthly_archive_pages_built) = "monthly archive pages built"
  msgstr(fr,monthly_archive_pages_built) = "index mensuels générés"
!
  msgstr(en,new_post) = "New post"
  msgstr(fr,new_post) = "Nouveau billet"
!
  msgstr(en,no_fblog_directory_at) = "No `fBlog' directory at"
  msgstr(fr,no_fblog_directory_at) = "Pas de répertoire `fBlog' à"
!
  msgstr(en,no_fblog_directory_here) = "No `fBlog' directory here."
  msgstr(fr,no_fblog_directory_here) = "Pas de répertoire `fBlog' ici."
!
  msgstr(en,no_post) = "No post."
  msgstr(fr,no_post) = "Pas de billet."
!
  msgstr(en,not_modified) = "Not modified."
  msgstr(fr,not_modified) = "Pas de modification."
!
  msgstr(en,now_you_could_edit_settings) = "Now, you could edit the menu in settings!"
  msgstr(fr,now_you_could_edit_settings) = "Maintenant, vous pourriez éditer le menu dans le fichier de configuration !"
!
  msgstr(en,now_you_should_update) = "Now, you should update!"
  msgstr(fr,now_you_should_update) = "Maintenant, vous devriez mettre à jour !"
!
  msgstr(en,pages) ="Pages..."
  msgstr(fr,pages) ="Pages..."
!
  msgstr(en,pages_built) = "pages built"
  msgstr(fr,pages_built) = "pages générées"
!
  msgstr(en,permalink_pages_built) = "permalink pages built"
  msgstr(fr,permalink_pages_built) = "permaliens générés"
!
  msgstr(en,posts) = "Posts..."
  msgstr(fr,posts) = "Billets..."
!
  msgstr(en,quit) = "Quit"
  msgstr(fr,quit) = "Quitter"
!
  msgstr(en,show_last_posts) = "Show last posts"
  msgstr(fr,show_last_posts) = "Liste des derniers billets"
!
  msgstr(en,show_full_list_css) = "Show list of style sheets"
  msgstr(fr,show_full_list_css) = "Liste des feuilles de style"
!
  msgstr(en,show_full_list_pages) = "Show list of pages"
  msgstr(fr,show_full_list_pages) = "Liste des pages"
!
  msgstr(en,show_full_list_posts) = "Show full list of posts"
  msgstr(fr,show_full_list_posts) = "Liste de tous les billets"
!
  msgstr(en,styles) = "Styles..."
  msgstr(fr,styles) = "Styles..."
!
  msgstr(en,the_folowing_files_and_directories_will_be_created) = "The folowing files and directories will be created:"
  msgstr(fr,the_folowing_files_and_directories_will_be_created) = "Les fichiers suivants vont être créés :"
!
  msgstr(en,there_is_already_a_blog) = "There is already a fBlog here!"
  msgstr(fr,there_is_already_a_blog) = "Il y a déjà un fBlog ici !"
!
  msgstr(en,there_is_not_directory) = "There is not directory"
  msgstr(fr,there_is_not_directory) = "Pas de répertoire"
!
  msgstr(en,this_file_doesnt_exist) = "This file doesn't exist."
  msgstr(fr,this_file_doesnt_exist) = "Pas de fichier à ce nom."
!
  msgstr(en,this_number_is_wrong) = "This number is wrong."
  msgstr(fr,this_number_is_wrong) = "Ce chiffre est incorrect."
!
  msgstr(en,too_much_arguments) = "Too much arguments."
  msgstr(fr,too_much_arguments) = "Arguments trop nombreux."
!
  msgstr(en,up) = "Up"
  msgstr(fr,up) = "Précédent"
!
  msgstr(en,update_all) = "Update all"
  msgstr(fr,update_all) = "Tout mettre à jour"
!
  msgstr(en,update_done) = "Update done"
  msgstr(fr,update_done) = "Mise à jour achevée"
!
  msgstr(en,shell_said) = "Shell said:"
  msgstr(fr,shell_said) = "Le shell dit :"
!
  msgstr(en,system_said) = "System said:"
  msgstr(fr,system_said) = "Le système dit :"
!
  msgstr(en,warn_about_no_css) = "Warning: no CSS defined. However, CSS file is optional."
  msgstr(fr,warn_about_no_css) = "ATTENTION : Pas de CSS définie. Toutefois, la feuille de style est facultative."
!
  msgstr(en,warn_about_no_css_print) = "Warning: no CSS for defined printer-friendly permalink pages.&
                                       & However, this CSS is optional."
  msgstr(fr,warn_about_no_css_print) = "ATTENTION : pas de CSS définie pour les permaliens imprimables. Toutefois, cette CSS &
                                       &est facultative."
!
  msgstr(en,wrong_entry) = "Wrong entry."
  msgstr(fr,wrong_entry) = "Mauvaise saisie."
!