! Copyright (C) 2016 Denis Bernard.
! Copyright (C) 2016 Vicente Merlo (for Portuguese translation).
! License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
! This is free software: you are free to change and redistribute it.
! There is NO WARRANTY, to the extent permitted by law.
! Written by Denis Bernard.
!
!! Internationalization of messages according setting of LANG (English, French...)
!
! English translator: Denis BERNARD
! French translator:  Denis BERNARD (mother tongue)
! Portuguese translator: Vicente Merlo
!
! Messages to be translated
!
  msgstr(en,bad_argument) = "Bad argument:"
  msgstr(fr,bad_argument) = "Mauvais argument :"
  msgstr(pt,bad_argument) = "Argumento inválido :"
!
  msgstr(en,begin_update) ="Begin update"
  msgstr(fr,begin_update) ="Début de la mise à jour"
  msgstr(pt,begin_update) ="Atualizando"
!
  msgstr(en,create_new_blog) = "Create new blog" 
  msgstr(fr,create_new_blog) = "Créer un nouveau blog"
  msgstr(pt,create_new_blog) = "Criar um novo blog" 
!
  msgstr(en,copy_css) = "Copy CSS to `"
  msgstr(fr,copy_css) = "Copie la feuille de style vers `"
  msgstr(pt,copy_css) = "Copiar folha de estilos para `"
!
  msgstr(en,copy_css_print) = "Copy CSS for printer to `"
  msgstr(fr,copy_css_print) = "Copie la feuille de style des permaliens imprimables vers `"
  msgstr(pt,copy_css_print) = "Copiar folha de estilos (páginas de impressão) para `"
!
  msgstr(en,deleted) = "deleted"
  msgstr(fr,deleted) = "effacé"
  msgstr(pt,deleted) = "removido"
!
  msgstr(en,delete_a_css) = "Delete a style sheet"
  msgstr(fr,delete_a_css) = "Supprimer une feuille de style"
  msgstr(pt,delete_a_css) = "Deletar uma folha de estilos"
!
  msgstr(en,delete_a_page) = "Delete a page"
  msgstr(fr,delete_a_page) = "Supprimer une page"
  msgstr(pt,delete_a_page) = "Remover uma página"
!
  msgstr(en,delete_a_post) = "Delete a post"
  msgstr(fr,delete_a_post) = "Supprimer un billet"  
  msgstr(pt,delete_a_post) = "Remover uma postagem"
!
  msgstr(en,deleted_file) = "Deleted file:"
  msgstr(fr,deleted_file) = "Supprimé le fichier :"
  msgstr(pt,deleted_file) = "Arquivo removido:"
!
  msgstr(en,deleted_page) = "Deleted page:"
  msgstr(fr,deleted_page) = "Supprimé la page :"
  msgstr(pt,deleted_page) = "Página removida :"
!
  msgstr(en,deleted_you_could_update_the_config) = "deleted. You could update the configuration file!"
  msgstr(fr,deleted_you_could_update_the_config) = "supprimé. Maintenant vous devriez mettre à jour la configuration !"
  msgstr(pt,deleted_you_could_update_the_config) = "removido. Você pode atualizar o arquivo de configuração!"
!
  msgstr(en,edit_a_page) = "New page or modify a page" 
  msgstr(fr,edit_a_page) = "Modifier ou créer une page" 
  msgstr(pt,edit_a_page) = "Modificar ou criar uma página" 
!
  msgstr(en,edit_a_css) = "New style sheet or modify a style sheet"
  msgstr(fr,edit_a_css) = "Modifier ou créer une feuille de style"
  msgstr(pt,edit_a_css) = "Nova folha de estilos ou modificar uma folha de estilos existente"
!
  msgstr(en,edited_page) = "Edited page:"
  msgstr(fr,edited_page) = "Édité la page :"
  msgstr(pt,edited_page) = "Editou a página:"
!
  msgstr(en,edit_settings) = "Edit settings"
  msgstr(fr,edit_settings) = "Configurer"
  msgstr(pt,edit_settings) = "Configurar"
!
  msgstr(en,end_clearing_subdirectory) = "End clearing subdirectory `"
  msgstr(fr,end_clearing_subdirectory) = "Fin du nettoyage du sous-répertoire `"
  msgstr(pt,end_clearing_subdirectory) = "Fim da limpeza do subdiretório `"
!
  msgstr(en,enter_the_filename_of_the_css_deleted) = "Enter the file name of the style sheet to be deleted:"
  msgstr(fr,enter_the_filename_of_the_css_deleted) = "Entrez le nom de fichier de la feuille de style à supprimer :"
  msgstr(pt,enter_the_filename_of_the_css_deleted) = "Entre com o nome do arquivo da folha de estilos a ser deletada:"
!
  msgstr(en,enter_the_filename_of_the_page_created) = "Enter the file name of the page to be created or modified:"
  msgstr(fr,enter_the_filename_of_the_page_created) = "Entrez le nom de fichier de la page à créer ou à modifier :"
  msgstr(pt,enter_the_filename_of_the_page_created) = "Entre com o nome do arquivo da página a ser criada ou modificada:"
!
  msgstr(en,enter_the_filename_of_the_page_deleted) = "Enter the file name of the page to be deleted:"
  msgstr(fr,enter_the_filename_of_the_page_deleted) = "Entrez le nom de fichier de la page à supprimer :"
  msgstr(pt,enter_the_filename_of_the_page_deleted) = "Entre com o nome do arquivo da página a ser deletada:"
!
  msgstr(en,enter_the_rank_of_the_post_to_delete) = "Enter the rank of the post to delete (the newest one is: < 1 >)"
  msgstr(fr,enter_the_rank_of_the_post_to_delete) = "Entrez le numéro du billet à supprimer (le  plus récent est : <1>)"
  msgstr(pt,enter_the_rank_of_the_post_to_delete) = "Entre com o número da postagem a ser deletada (a mais recente é: <1>)"
!
  msgstr(en,enter_the_rank_of_the_post_to_modify) = "Enter the rank of the post to modify (the newest one is: < 1 >)"
  msgstr(fr,enter_the_rank_of_the_post_to_modify) = "Entrez le numéro du billet à modifier (le plus récent est : <1>)"
  msgstr(pt,enter_the_rank_of_the_post_to_modify) = "Entre com o número da postagem a ser modificada (a mais recente é: <1>)"
!
  msgstr(en,error_css) = "Erroneous CSS name. Please, verify the configuration file."
  msgstr(fr,error_css) = "Nom de la CSS erronnée. Merci de vérifier le fichier de configuration."
  msgstr(pt,error_css) = "Nome do CSS incorreto. Por favor, verifique o arquivo de configuração."
!
  msgstr(en,error_css_print) = "Erroneous name CSS for printer. Verify configuration file."
  msgstr(fr,error_css_print) = "Nom de la CSS pour l'imprimante erroné. Merci de vérifier le fichier de configuration."
  msgstr(pt,error_css_print) = "Nome do CSS para impressão incorreto. Por favor, verifique o arquivo de configuração."
!
  msgstr(en,files_generated_inside_the_subdirectory) = "files generated within the subdirectory `"
  msgstr(fr,files_generated_inside_the_subdirectory) = "fichiers générés dans le sous-répertoire `"
  msgstr(pt,files_generated_inside_the_subdirectory) = "arquivos gerados dentro do subdiretório `"
!
  msgstr(en,initialisation_reading_conf) = "Initialisation 2/2: reading configuration"
  msgstr(fr,initialisation_reading_conf) = "Initialisation 2/2: lecture de la configuration"
  msgstr(pt,initialisation_reading_conf) = "Inicializando 2/2: lendo configurações"
!
  msgstr(en,initialisation_reading_data) = "Initialisation 1/2: reading data"
  msgstr(fr,initialisation_reading_data) = "Initialisation 1/2 : lecture des données"
  msgstr(pt,initialisation_reading_data) = "Inicializando 1/2: lendo dados"
!
  msgstr(en,is_a_wrong_argument) = "is a wrong argument."
  msgstr(fr,is_a_wrong_argument) = "est un mauvais argument."  
  msgstr(pt,is_a_wrong_argument) = "é um argumento inválido."
!
  msgstr(en,is_deleted) = "deleted:"
  msgstr(fr,is_deleted) = "effacé :"
  msgstr(pt,is_deleted) = "removido:"
!
  msgstr(en,make_archive_pages) = "Make archive page `"
  msgstr(fr,make_archive_pages) = "Génère l'index des archives `"
  msgstr(pt,make_archive_pages) = "Gerar página de índice `"
!
  msgstr(en,make_clear_subdirectory) = "Make clear subdirectory `"
  msgstr(fr,make_clear_subdirectory) = "Début du nettoyage du sous-répertoire `"
  msgstr(pt,make_clear_subdirectory) = "Limpar subdiretório `"
!
  msgstr(en,make_home_page) = "Make home page `"
  msgstr(fr,make_home_page) = "Génère la page d'accueil `"
  msgstr(pt,make_home_page) = "Gerar página principal `"
!
  msgstr(en,make_pages) = "Make pages `"
  msgstr(fr,make_pages) = "Génère les pages statiques `"
  msgstr(pt,make_pages) = "Gerar páginas `"
!
  msgstr(en,make_permalink_pages) = "Make permalink pages `"
  msgstr(fr,make_permalink_pages) = "Génère les permaliens `"
  msgstr(pt,make_permalink_pages) = "Gerar páginas de permalink `"
!
  msgstr(en,modify_a_post) = "Modify a post"
  msgstr(fr,modify_a_post) = "Modifier un billet"
  msgstr(pt,modify_a_post) = "Modificar uma postagem"
!
  msgstr(en,monthly_archive_pages_built) = "monthly archive pages built"
  msgstr(fr,monthly_archive_pages_built) = "index mensuels générés"
  msgstr(pt,monthly_archive_pages_built) = "página de índices mensal gerada"
!
  msgstr(en,new_post) = "New post"
  msgstr(fr,new_post) = "Nouveau billet"
  msgstr(pt,new_post) = "Nova postagem"
!
  msgstr(en,no_fblog_directory_at) = "No `fBlog' directory at"
  msgstr(fr,no_fblog_directory_at) = "Pas de répertoire `fBlog' à"
  msgstr(pt,no_fblog_directory_at) = "Diretório `fBlog' não encontrado em"
!
  msgstr(en,no_fblog_directory_here) = "No `fBlog' directory here."
  msgstr(fr,no_fblog_directory_here) = "Pas de répertoire `fBlog' ici."
  msgstr(pt,no_fblog_directory_here) = "O diretório `fBlog' não existe neste caminho."
!
  msgstr(en,no_post) = "No post."
  msgstr(fr,no_post) = "Pas de billet."
  msgstr(pt,no_post) = "Nenhuma postagem."
!
  msgstr(en,not_modified) = "Not modified."
  msgstr(fr,not_modified) = "Pas de modification."
  msgstr(pt,not_modified) = "Não modificado."
!
  msgstr(en,now_you_could_edit_settings) = "Now, you could edit the menu in settings!"
  msgstr(fr,now_you_could_edit_settings) = "Maintenant, vous pourriez éditer le menu dans le fichier de configuration !"
  msgstr(pt,now_you_could_edit_settings) = "Agora, você pode editar o menu nas configurações!"
!
  msgstr(en,now_you_should_update) = "Now, you should update!"
  msgstr(fr,now_you_should_update) = "Maintenant, vous devriez mettre à jour !"
  msgstr(pt,now_you_should_update) = "Agora, você deve atualizar!"
!
  msgstr(en,pages) ="Pages..."
  msgstr(fr,pages) ="Pages..."
  msgstr(pt,pages) ="Páginas..."
!
  msgstr(en,pages_built) = "pages built"
  msgstr(fr,pages_built) = "pages générées"
  msgstr(pt,pages_built) = "páginas geradas"
!
  msgstr(en,permalink_pages_built) = "permalink pages built"
  msgstr(fr,permalink_pages_built) = "permaliens générés"
  msgstr(pt,permalink_pages_built) = "páginas de permalink geradas"
!
  msgstr(en,posts) = "Posts..."
  msgstr(fr,posts) = "Billets..."
  msgstr(pt,posts) = "Postagens..."
!
  msgstr(en,quit) = "Quit"
  msgstr(fr,quit) = "Quitter"
  msgstr(pt,quit) = "Sair"
!
  msgstr(en,show_last_posts) = "Show last posts"
  msgstr(fr,show_last_posts) = "Liste des derniers billets"
  msgstr(pt,show_last_posts) = "Mostrar últimas postagens"
!
  msgstr(en,show_full_list_css) = "Show list of style sheets"
  msgstr(fr,show_full_list_css) = "Liste des feuilles de style"
  msgstr(pt,show_full_list_css) = "Mostrar lista de folhas de estilo"
!
  msgstr(en,show_full_list_pages) = "Show list of pages"
  msgstr(fr,show_full_list_pages) = "Liste des pages"
  msgstr(pt,show_full_list_pages) = "Mostrar lista de páginas"
!
  msgstr(en,show_full_list_posts) = "Show full list of posts"
  msgstr(fr,show_full_list_posts) = "Liste de tous les billets"
  msgstr(pt,show_full_list_posts) = "Mostrar lista completa de postagens"
!
  msgstr(en,styles) = "Styles..."
  msgstr(fr,styles) = "Styles..."
  msgstr(pt,styles) = "Estilos..."
!
  msgstr(en,the_folowing_files_and_directories_will_be_created) = "The folowing files and directories will be created:"
  msgstr(fr,the_folowing_files_and_directories_will_be_created) = "Les fichiers suivants vont être créés :"
  msgstr(pt,the_folowing_files_and_directories_will_be_created) = "Os seguintes arquivos e diretórios serão criados:"
!
  msgstr(en,there_is_already_a_blog) = "There is already a fBlog here!"
  msgstr(fr,there_is_already_a_blog) = "Il y a déjà un fBlog ici !"
  msgstr(pt,there_is_already_a_blog) = "Já existe um fBlog aqui!"
!
  msgstr(en,there_is_not_directory) = "There is not directory"
  msgstr(fr,there_is_not_directory) = "Pas de répertoire"
  msgstr(pt,there_is_not_directory) = "Não há um diretório"
!
  msgstr(en,this_file_doesnt_exist) = "This file doesn't exist."
  msgstr(fr,this_file_doesnt_exist) = "Pas de fichier à ce nom."
  msgstr(pt,this_file_doesnt_exist) = "Esse arquivo não existe."
!
  msgstr(en,this_number_is_wrong) = "This number is wrong."
  msgstr(fr,this_number_is_wrong) = "Ce chiffre est incorrect."
  msgstr(pt,this_number_is_wrong) = "Esse número está incorreto."
!
  msgstr(en,too_much_arguments) = "Too much arguments."
  msgstr(fr,too_much_arguments) = "Arguments trop nombreux."
  msgstr(pt,too_much_arguments) = "Número de argumentos inválido."
!
  msgstr(en,up) = "Up"
  msgstr(fr,up) = "Précédent"
  msgstr(pt,up) = "Anterior"
!
  msgstr(en,update_all) = "Update all"
  msgstr(fr,update_all) = "Tout mettre à jour"
  msgstr(pt,update_all) = "Atualizar tudo"
!
  msgstr(en,update_done) = "Update done"
  msgstr(fr,update_done) = "Mise à jour achevée"
  msgstr(pt,update_done) = "Atualização completa"
!
  msgstr(en,shell_said) = "Shell said:"
  msgstr(fr,shell_said) = "Le shell dit :"
  msgstr(pt,shell_said) = "A shell disse:"
!
  msgstr(en,system_said) = "System said:"
  msgstr(fr,system_said) = "Le système dit :"
  msgstr(pt,system_said) = "O sistema disse:"
!
  msgstr(en,warn_about_no_css) = "Warning: no CSS defined. However, CSS file is optional."
  msgstr(fr,warn_about_no_css) = "ATTENTION : Pas de CSS définie. Toutefois, la feuille de style est facultative."
  msgstr(pt,warn_about_no_css) = "ATENÇÃO: nenhum CSS definido. Todavia, o arquivo de estilos é opcional."
!
  msgstr(en,warn_about_no_css_print) = "Warning: no CSS for defined printer-friendly permalink pages.&
                                       & However, this CSS is optional."
  msgstr(fr,warn_about_no_css_print) = "ATTENTION : pas de CSS définie pour les permaliens imprimables. Toutefois, cette CSS &
                                       &est facultative."
  msgstr(pt,warn_about_no_css_print) = "ATENÇÃO: nenhum CSS definido para páginas de impressão de permalink. Porém, esse CSS&
                                       & é opcional."
!
  msgstr(en,wrong_entry) = "Wrong entry."
  msgstr(fr,wrong_entry) = "Mauvaise saisie."
  msgstr(pt,wrong_entry) = "Entrada inválida."
!
! Translators' name
!
  msgstr(en,translator) = "Denis Bernard"
  msgstr(fr,translator) = "Denis Bernard"
  msgstr(pt,translator) = "Vicente Merlo"
!

