   'Lorem ipsum' //  new_line('a') // &         
   '<p>' // new_line('a') // &   
   'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non' // new_line('a') // &   
   'risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec,' // new_line('a') // &   
   'ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula' // new_line('a') // &   
   'massa, varius a, semper congue, euismod non, mi. Proin porttitor,' // new_line('a') // &   
   'orci nec nonummy molestie, enim est eleifend mi, non fermentum diam' // new_line('a') // &   
   'nisl sit amet erat. Duis semper. Duis arcu massa, scelerisque vitae,' // new_line('a') // &   
   'consequat in, pretium a, enim. Pellentesque congue. Ut in risus' // new_line('a') // &   
   'volutpat libero pharetra tempor. Cras vestibulum bibendum augue.' // new_line('a') // &   
   'Praesent egestas leo in pede. Praesent blandit odio eu enim.' // new_line('a') // &   
   'Pellentesque sed dui ut augue blandit sodales. Vestibulum ante ipsum' // new_line('a') // &   
   'primis in faucibus orci luctus et ultrices posuere cubilia Curae;' // new_line('a') // &   
   'Aliquam nibh. Mauris ac mauris sed pede pellentesque fermentum.' // new_line('a') // &   
   'Maecenas adipiscing ante non diam sodales hendrerit.' // new_line('a') // &   
   '</p>' // new_line('a') // &   
   '<p>' // new_line('a') // &   
   'Ut velit mauris, egestas sed, gravida nec, ornare ut, mi. Aenean ut' // new_line('a') // &   
   'orci vel massa suscipit pulvinar. Nulla sollicitudin. Fusce varius,' // new_line('a') // &   
   'ligula non tempus aliquam, nunc turpis ullamcorper nibh, in tempus' // new_line('a') // &   
   'sapien eros vitae ligula. Pellentesque rhoncus nunc et augue. Integer' // new_line('a') // &   
   'id felis. Curabitur aliquet pellentesque diam. Integer quis metus' // new_line('a') // &   
   'vitae elit lobortis egestas. Lorem ipsum dolor sit amet, consectetuer' // new_line('a') // &   
   'adipiscing elit. Morbi vel erat non mauris convallis vehicula. Nulla et' // new_line('a') // &   
   'sapien. Integer tortor tellus, aliquam faucibus, convallis id, congue' // new_line('a') // &   
   'eu, quam. Mauris ullamcorper felis vitae erat. Proin feugiat, augue' // new_line('a') // &   
   'non elementum posuere, metus purus iaculis lectus, et tristique ligula' // new_line('a') // &   
   'justo vitae magna.' // new_line('a') // &   
   '</p>' // new_line('a') // &   
   '<p>' // new_line('a') // &   
   'Aliquam convallis sollicitudin purus. Praesent aliquam, enim at' // new_line('a') // &   
   'fermentum mollis, ligula massa adipiscing nisl, ac euismod nibh nisl' // new_line('a') // &   
   'eu lectus. Fusce vulputate sem at sapien. Vivamus leo. Aliquam euismod' // new_line('a') // &   
   'libero eu enim. Nulla nec felis sed leo placerat imperdiet. Aenean' // new_line('a') // &   
   'suscipit nulla in justo. Suspendisse cursus rutrum augue. Nulla' // new_line('a') // &   
   'tincidunt tincidunt mi. Curabitur iaculis, lorem vel rhoncus faucibus,' // new_line('a') // &   
   'felis magna fermentum augue, et ultricies lacus lorem varius purus.' // new_line('a') // &   
   'Curabitur eu amet.' // new_line('a') // &   
   '</p>' // new_line('a') // &   
   '<hr />' // new_line('a') // &   
   '<p><samp><mark>&lt;p></mark></samp>' // new_line('a') // &   
   'Aliquam convallis sollicitudin purus. Praesent aliquam, enim at' // new_line('a') // &   
   'fermentum mollis, ligula massa adipiscing nisl, ac euismod nibh nisl' // new_line('a') // &   
   'eu lectus. Fusce vulputate sem at sapien. Vivamus leo. Aliquam' // new_line('a') // &   
   'euismod libero eu enim. Nulla nec felis sed leo placerat imperdiet.' // new_line('a') // &   
   'Aenean suscipit nulla in justo. Suspendisse cursus rutrum augue.' // new_line('a') // &   
   'Nulla tincidunt tincidunt mi. Curabitur iaculis, lorem vel rhoncus' // new_line('a') // &   
   'faucibus,felis magna fermentum augue, et ultricies lacus lorem varius' // new_line('a') // &   
   'purus. Curabitur eu amet.' // new_line('a') // &   
   '<samp><mark>&lt;/p></mark></samp></p>' // new_line('a') // &   
   'Lorem ipsum <samp><mark>&lt;q></mark></samp> <q>dolor</q> <samp>' // new_line('a') // &   
   '<mark>&lt;/q></mark></samp> sit amet<br />' // new_line('a') // &   
   'Lorem ipsum <samp><mark>&lt;em></mark></samp> <em>dolor</em> <samp>' // new_line('a') // &   
   '<mark>&lt;/em></mark></samp> sit amet<br />' // new_line('a') // &   
   'Lorem ipsum <samp><mark>&lt;i></mark></samp> <i>dolor</i> <samp>' // new_line('a') // &   
   '<mark>&lt;/i></mark></samp> sit amet<br />' // new_line('a') // &   
   'Lorem ipsum <samp><mark>&lt;cite></mark></samp> <cite>dolor</cite>' // new_line('a') // &   
   '<samp><mark>&lt;/cite></mark></samp> sit amet<br />' // new_line('a') // &   
   'Lorem ipsum <samp><mark>&lt;kbd></mark></samp> <kbd>dolor</kbd>' // new_line('a') // &   
   ' <samp><mark>&lt;/kbd></mark></samp> sit amet<br />' // new_line('a') // &   
   'Lorem ipsum <samp><mark>&lt;abbr></mark></samp> <abbr>dolor</abbr>' // new_line('a') // &   
   ' <samp><mark>&lt;/abbr></mark></samp> sit amet<br />' // new_line('a') // &   
   'Lorem ipsum <samp><mark>&lt;dfn></mark></samp> <dfn>dolor</dfn>' // new_line('a') // &   
   ' <samp><mark>&lt;/dfn></mark></samp> sit amet<br />' // new_line('a') // &   
   'Lorem ipsum <samp><mark>&lt;strong></mark></samp> <strong>dolor' // new_line('a') // &   
   '</strong> <samp><mark>&lt;/strong></mark></samp> sit amet<br />' // new_line('a') // &   
   'Lorem ipsum <samp><mark>&lt;b></mark></samp> <b>dolor</b> <samp>' // new_line('a') // &   
   '<mark>&lt;/b></mark></samp> sit amet<br />' // new_line('a') // &   
   'Lorem ipsum <samp><mark>&lt;small></mark></samp> <small>dolor</small>' // new_line('a') // &   
   ' <samp><mark>&lt;/small></mark></samp> sit amet<br />' // new_line('a') // &   
   'Lorem ipsum <samp><mark>&lt;sup></mark></samp> <sup>dolor</sup>' // new_line('a') // &   
   ' <samp><mark>&lt;/sup></mark></samp> sit amet<br />' // new_line('a') // &   
   'Lorem ipsum <samp><mark>&lt;sub></mark></samp> <sub>dolor</sub>' // new_line('a') // &   
   ' <samp><mark>&lt;/sub></mark></samp> sit amet<br />' // new_line('a') // &   
   'Lorem ipsum <samp><mark>&lt;u></mark></samp> <u>dolor</u> <samp>' // new_line('a') // &   
   '<mark>&lt;/u></mark></samp> sit amet<br />' // new_line('a') // &   
   'Lorem ipsum <samp><mark>&lt;ins></mark></samp> <ins>dolor</ins>' // new_line('a') // &   
   ' <samp><mark>&lt;/ins></mark></samp> sit amet<br />' // new_line('a') // &   
   'Lorem ipsum <samp><mark>&lt;del></mark></samp> <del>dolor</del>' // new_line('a') // &   
   ' <samp><mark>&lt;/del></mark></samp> sit amet<br />' // new_line('a') // &   
   'Lorem ipsum <samp><mark>&lt;s></mark></samp> <s>dolor</s> <samp>' // new_line('a') // &   
   '<mark>&lt;/s></mark></samp> sit amet<br />' // new_line('a') // &   
   'Lorem ipsum <samp><mark style="background-color:transparent; border:' // new_line('a') // &   
   '#ff9040 solid medium;">&lt;mark></mark></samp> <mark>dolor</mark>' // new_line('a') // &   
   ' <samp>' // new_line('a') // &   
   '<mark style="background-color:transparent; border:#ff9040 solid' // new_line('a') // &   
   ' medium;">&lt;/mark></mark></samp> sit amet<br />' // new_line('a') // &   
   'Lorem ipsum <samp><mark>&lt;a href="http://www.example.com"></mark>' // new_line('a') // &   
   '</samp> <a href="http://www.example.com">dolor</a>  <samp><mark>&lt;/a></mark></samp> sit amet<br />' // new_line('a') // &
   '<hr />' // new_line('a') // &   
   '<samp><mark>&lt;dl></mark></samp>' // new_line('a') // &   
   '<dl>' // new_line('a') // &   
   '<dt><samp><mark>&lt;dt></mark></samp> Lorem ipsum <samp>' // new_line('a') // &   
   '<mark>&lt;/dt></mark></samp></dt>' // new_line('a') // &   
   '<dd><samp><mark>&lt;dd></mark></samp> Lorem ipsum <samp>' // new_line('a') // &   
   '<mark>&lt;/dd></mark></samp></dd>' // new_line('a') // &   
   '<dt><samp><mark>&lt;dt></mark></samp> Lorem ipsum <samp>' // new_line('a') // &   
   '<mark>&lt;/dt></mark></samp></dt>' // new_line('a') // &   
   '<dd><samp><mark>&lt;dd></mark></samp> Lorem ipsum <samp>' // new_line('a') // &   
   '<mark>&lt;/dd></mark></samp></dd>' // new_line('a') // &   
   '</dl>' // new_line('a') // &   
   '<samp><mark>&lt;/dl></mark></samp>' // new_line('a') // &   
   '<hr />' // new_line('a') // &   
   '<samp><mark>&lt;ul></mark></samp>' // new_line('a') // &   
   '<ul>' // new_line('a') // &   
   '<li><samp><mark>&lt;li></mark></samp> Lorem ipsum <samp>' // new_line('a') // &   
   '<mark>&lt;/li></mark></samp></li>' // new_line('a') // &   
   '<li><samp><mark>&lt;li></mark></samp> Lorem ipsum <samp>' // new_line('a') // &   
   '<mark>&lt;/li></mark></samp></li>' // new_line('a') // &   
   '<li><samp><mark>&lt;li></mark></samp> Lorem ipsum <samp>' // new_line('a') // &   
   '<mark>&lt;/li></mark></samp></li>' // new_line('a') // &   
   '</ul>' // new_line('a') // &   
   '<samp><mark>&lt;/ul></mark></samp>' // new_line('a') // &   
   '<hr />' // new_line('a') // &   
   '<samp><mark>&lt;ol></mark></samp>' // new_line('a') // &   
   '<ol>' // new_line('a') // &   
   '<li><samp><mark>&lt;li></mark></samp> Lorem ipsum <samp>' // new_line('a') // &   
   '<mark>&lt;/li></mark></samp></li>' // new_line('a') // &   
   '<li><samp><mark>&lt;li></mark></samp> Lorem ipsum <samp>' // new_line('a') // &   
   '<mark>&lt;/li></mark></samp></li>' // new_line('a') // &   
   '<li><samp><mark>&lt;li></mark></samp> Lorem ipsum <samp>' // new_line('a') // &   
   '<mark>&lt;/li></mark></samp></li>' // new_line('a') // &   
   '</ol>' // new_line('a') // &   
   '<samp><mark>&lt;/ol></mark></samp>' // new_line('a') // &   
   '<hr />' // new_line('a') // &   
   '<samp><mark>&lt;h6></mark></samp><h6 style="display:inline"> Lorem' // new_line('a') // &   
   ' ipsum </h6><samp><mark>&lt;/h6></mark></samp><br />' // new_line('a') // &   
   '<samp><mark>&lt;h5></mark></samp><h5 style="display:inline"> Lorem' // new_line('a') // &   
   ' ipsum </h5><samp><mark>&lt;/h5></mark></samp><br />' // new_line('a') // &   
   '<samp><mark>&lt;h4></mark></samp><h4 style="display:inline"> Lorem' // new_line('a') // &   
   ' ipsum </h4><samp><mark>&lt;/h4></mark></samp><br />' // new_line('a') // &   
   '<samp><mark>&lt;h3></mark></samp><h3 style="display:inline"> Lorem' // new_line('a') // &   
   ' ipsum </h3><samp><mark>&lt;/h3></mark></samp><br />' // new_line('a') // &   
   '<samp><mark>&lt;h2></mark></samp><h2 style="display:inline"> Lorem' // new_line('a') // &   
   ' ipsum </h2><samp><mark>&lt;/h2></mark></samp><br />' // new_line('a') // &   
   '<hr />' // new_line('a') // &   
   '<samp><mark>&lt;pre></mark></samp><pre>' // new_line('a') // &   
   'Aliquam convallis sollicitudin purus. Praesent aliquam, enim at' // new_line('a') // &   
   'fermentum mollis, ligula massa adipiscing nisl, ac euismod nibh nisl' // new_line('a') // &   
   'eu lectus. Fusce vulputate sem at sapien. Vivamus leo. Aliquam' // new_line('a') // &   
   'euismod libero eu enim. Nulla nec felis sed leo placerat imperdiet.' // new_line('a') // &   
   'Aenean suscipit nulla in justo. Suspendisse cursus rutrum augue.' // new_line('a') // &   
   'Nulla tincidunt tincidunt mi. Curabitur iaculis, lorem vel rhoncus' // new_line('a') // &   
   'faucibus, felis magna fermentum augue, et ultricies lacus lorem' // new_line('a') // &   
   'varius purus. Curabitur eu amet.' // new_line('a') // &   
   '</pre><samp><mark>&lt;/pre></mark></samp>' // new_line('a') // &   
   '<hr />' // new_line('a') // &   
   '<samp><mark>&lt;samp></mark></samp> <samp>character(len=15) function' // new_line('a') // &   
   'clock()</samp> <samp><mark>&lt;/samp></mark></samp><br />' // new_line('a') // &   
   '<hr />' // new_line('a') // &   
   '<samp><mark>&lt;pre>&lt;code></mark></samp>' // new_line('a') // &   
   '<pre><code>' // new_line('a') // &   
   '!'                                                                                     // new_line('a') // &   
   '!  &lt;----------------------------- code ---------------------------------------->'   // new_line('a') // &   
   '!'                                                                                     // new_line('a') // &   
   '      character(len=15) function clock()'                                              // new_line('a') // &   
   '!'                                                                                     // new_line('a') // &   
   '!  ------------------------------ head -----------------------------------------'      // new_line('a') // &   
   '   character(len=10) :: raw_clock'                                                     // new_line('a') // &   
   '!  ------------------------------ body -----------------------------------------'      // new_line('a') // &   
   '   call date_and_time(                                                         &'      // new_line('a') // &   
   '      time = raw_clock                                                         &'      // new_line('a') // &   
   '      )'                                                                               // new_line('a') // &   
   "   clock = '[' // raw_clock(1:2) // ':' // raw_clock(3:4) // ':'               &"      // new_line('a') // &   
   "           // raw_clock (5:10) // ']'                                           "      // new_line('a') // &   
   '!  -----------------------------------------------------------------------------'      // new_line('a') // &   
   '!'                                                                                     // new_line('a') // &   
   '      end function clock'                                                              // new_line('a') // &   
   '!'                                                                                     // new_line('a') // &   
   '!  &lt;----------------------------- code ---------------------------------------->'   // new_line('a') // &   
   '!'                                                                                     // new_line('a') // &   
   '</code></pre>' // new_line('a') // &   
   '<samp><mark>&lt;/pre>&lt;/code></mark></samp>' // new_line('a') // &   
   '<hr />' // new_line('a') // &   
   '<samp><mark>&lt;blockquote></mark></samp><blockquote>' // new_line('a') // &   
   'Aliquam convallis sollicitudin purus. Praesent aliquam, enim at' // new_line('a') // &   
   'fermentum mollis, ligula massa adipiscing nisl, ac euismod nibh nisl' // new_line('a') // &   
   'eu lectus. Fusce vulputate sem at sapien. Vivamus leo. Aliquam euismod' // new_line('a') // &   
   'libero eu enim. Nulla nec felis sed leo placerat imperdiet. Aenean' // new_line('a') // &   
   'suscipit nulla in justo. Suspendisse cursus rutrum augue. Nulla' // new_line('a') // &   
   'tincidunt tincidunt mi. Curabitur iaculis, lorem vel rhoncus faucibus,' // new_line('a') // &   
   'felis magna fermentum augue, et ultricies lacus lorem varius purus.' // new_line('a') // &   
   'Curabitur eu amet.<br />' // new_line('a') // &   
   '</blockquote><samp><mark>&lt;/blockquote></mark></samp>' // new_line('a') // &   
   '<hr />' // new_line('a') // &   
   '<samp><mark>&lt;address></mark></samp><address>Aliquam Convallis' // new_line('a') // &   
   ' <samp><mark>&lt;br /></mark></samp><br />' // new_line('a') // &   
   'Nulla nec felis sed  <samp><mark>&lt;br /></mark></samp><br />' // new_line('a') // &   
   'Aenean' // new_line('a') // &   
   '</address><samp><mark>&lt;/address></mark></samp><hr />' // new_line('a') // &   
   '<samp><mark>&lt;hr style="width:30%" /></mark></samp> <hr' // new_line('a') // &   
   ' style="width:30%;margin-top:-0.7ex;"/>'